[project]
name = "cer-fact-checking"
version = "0.1.0"
description = "Add your description here"
requires-python = "==3.11.*"
dependencies = [
    "ago==0.0.95",
    "aiohappyeyeballs==2.4.4",
    "aiohttp==3.11.11",
    "aiosignal==1.3.2",
    "altair==5.5.0",
    "annotated-types==0.7.0",
    "anyio==4.8.0",
    "async-timeout==5.0.1",
    "attrs==24.3.0",
    "automat==24.8.1",
    "beautifulsoup4==4.12.3",
    "blinker==1.9.0",
    "boto3==1.36.5",
    "botocore==1.36.5",
    "bs4==0.0.2",
    "cachetools==5.5.0",
    "certifi==2024.12.14",
    "cffi==1.17.1",
    "chardet==5.2.0",
    "charset-normalizer==3.4.1",
    "click==8.1.8",
    "colorama==0.4.6",
    "constantly==23.10.4",
    "contourpy==1.3.0",
    "cryptography==44.0.0",
    "cssselect==1.2.0",
    "cycler==0.12.1",
    "decorator==5.1.1",
    "defusedxml==0.7.1",
    "distro==1.9.0",
    "dotmap==1.3.30",
    "elastic-transport==8.17.0",
    "elasticsearch==8.17.1",
    "exceptiongroup==1.2.2",
    "faiss-cpu==1.7.4",
    "faust-cchardet==2.1.19",
    "feedparser==6.0.11",
    "ffmpeg-python==0.2.0",
    "filelock==3.16.1",
    "fonttools==4.55.5",
    "frozenlist==1.5.0",
    "fsspec==2024.12.0",
    "future==1.0.0",
    "gitdb==4.0.12",
    "gitpython==3.1.44",
    "h11==0.14.0",
    "hjson==3.1.0",
    "htbuilder==0.9.0",
    "httpcore==1.0.7",
    "httpx==0.28.1",
    "huggingface-hub==0.17.3",
    "hurry-filesize==0.9",
    "hyperlink==21.0.0",
    "idna==3.10",
    "imageio==2.37.0",
    "imageio-ffmpeg==0.6.0",
    "importlib-metadata==6.11.0",
    "incremental==24.7.2",
    "itemadapter==0.10.0",
    "itemloaders==1.3.2",
    "jinja2==3.1.5",
    "jiter==0.8.2",
    "jmespath==1.0.1",
    "joblib==1.4.2",
    "jsonschema==4.23.0",
    "jsonschema-specifications==2024.10.1",
    "kiwisolver==1.4.7",
    "langdetect==1.0.9",
    "llvmlite==0.43.0",
    "lxml==5.3.0",
    "lxml-html-clean==0.4.1",
    "markdown-it-py==3.0.0",
    "markupsafe==3.0.2",
    "matplotlib==3.9.4",
    "mdurl==0.1.2",
    "more-itertools==10.6.0",
    "moviepy==2.1.2",
    "mpmath==1.3.0",
    "multidict==6.1.0",
    "narwhals==1.22.0",
    "networkx==3.2.1",
    "news-please==1.6.13",
    "newspaper4k==0.9.3.1",
    "nltk==3.9.1",
    "numba==0.60.0",
    "numpy==1.26.4",
    "openai==1.59.9",
    "openai-whisper",
    "packaging==23.2",
    "pandas>=2.1.0",
    "parsel==1.10.0",
    "pillow==9.5.0",
    "plac==1.4.3",
    "prettytable==3.13.0",
    "proglog==0.1.10",
    "propcache==0.2.1",
    "protego==0.4.0",
    "protobuf==4.25.5",
    "psycopg2-binary==2.9.10",
    "pyarrow==19.0.0",
    "pyasn1==0.6.1",
    "pyasn1-modules==0.4.1",
    "pycparser==2.22",
    "pydantic==2.10.5",
    "pydantic-core==2.27.2",
    "pydeck==0.9.1",
    "pydispatcher==2.0.7",
    "pyecharts==2.0.8",
    "pygments==2.19.1",
    "pympler==1.1",
    "pymysql==1.1.1",
    "pyopenssl==25.0.0",
    "pyparsing==3.2.1",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.0.1",
    "pytz==2024.2",
    "pytz-deprecation-shim==0.1.0.post0",
    "pywin32==308",
    "pyyaml==6.0.2",
    "queuelib==1.7.0",
    "readability-lxml==0.8.1",
    "redis==5.2.1",
    "referencing==0.35.1",
    "regex==2024.11.6",
    "requests==2.32.3",
    "requests-file==2.1.0",
    "rich==13.9.4",
    "rpds-py==0.22.3",
    "s3transfer==0.11.2",
    "safetensors==0.5.2",
    "scikit-learn==1.6.1",
    "scipy==1.13.1",
    "scrapy==2.12.0",
    "sentence-transformers==2.2.2",
    "sentencepiece==0.2.0",
    "service-identity==24.2.0",
    "sgmllib3k==1.0.0",
    "simplejson==3.19.3",
    "six==1.17.0",
    "smmap==5.0.2",
    "sniffio==1.3.1",
    "soupsieve==2.6",
    "st-annotated-text==4.0.1",
    "streamlit==1.41.1",
    "streamlit-echarts==0.4.0",
    "streamlit-option-menu==0.4.0",
    "streamlit-scrollable-textbox==0.0.3",
    "sympy==1.13.1",
    "tenacity==8.5.0",
    "threadpoolctl==3.5.0",
    "tiktoken==0.8.0",
    "tldextract==5.1.3",
    "tokenizers==0.14.1",
    "toml==0.10.2",
    "tomli==2.2.1",
    "torch==2.5.1",
    "torchvision==0.20.1",
    "tornado==6.4.2",
    "tqdm==4.67.1",
    "transformers==4.34.0",
    "twisted==24.11.0",
    "typing-extensions==4.12.2",
    "tzdata==2024.2",
    "tzlocal==4.3.1",
    "urllib3==1.26.2",
    "utils==1.0.2",
    "validators==0.34.0",
    "w3lib==2.2.1",
    "warcio==1.7.5",
    "watchdog==6.0.0",
    "wcwidth==0.2.13",
    "yarl==1.18.3",
    "zipp==3.21.0",
    "zope-interface==7.2",
]

[tool.uv.sources]
openai-whisper = { git = "https://github.com/openai/whisper.git" }
